### ISSUE TITLE
canSwipe not called when button is shown

### ISSUE THREAD

**Issue by messiahluo** [MortimerGoro/MGSwipeTableCell#100]
I have a cell have a leftButton and a rightButton, I only want the leftButton show on some conditions, so I override the canSwipe method like this:
     
    return (direction == MGSwipeDirectionLeftToRight && shouldLeftButtonShown);

when the cell is in normal state, it's working great, but when I swipe right to left first, now cell is showing my rightButton, then I swipe left to right, the leftButton comes out unexpectly, and the breakpoint in canSwipe method is not been hit. 

I think it is a bug in here or I need to do some extra stuff to make this work? 

And thanks for the the great work! It really make life easier.

**Comment by MortimerGoro** [comment]
Fixed in develop branch, I will merge to master & CocoaPods in the next release

**Comment by MortimerGoro** [comment]
Fixed in 1.5.1

**Comment by messiahluo** [comment]
Thx for the work!
