### ISSUE TITLE
Don't want to hideSwipe when user hit overlay

### ISSUE THREAD

**Issue by ppjia** [MortimerGoro/MGSwipeTableCell#104]
I have been using MGSwipeTableCell for a while in my project, it's awesome!
Now I have a requirement regarding overlay hitting, I don't want to hide swipe every time when user hit the overlay, the hidden should happen depend on cell.
As I investigated the code, I suppose we can add one delegate method to identify whether the hidden should happen on overlay hitting, and check this method in MGSwipeTableInputOverlay's hitTest method.
Or is there another way to achieve this?
Thanks!

**Comment by MortimerGoro** [comment]
Hi,

I have implemented a new delegate method. Now you can decide when to hide the swipe when the user taps the cell ;)

It's available in develop branch. I will merge to master in the next release.

´´´
-(BOOL) swipeTableCell:(MGSwipeTableCell *)cell shouldHideSwipeOnTap:(CGPoint) point
{
    NSLog(@"Point %f %f", point.x, point.y);
    return NO;
}
´´´

**Comment by MortimerGoro** [comment]
Available in 1.5.1

**Comment by LucasCoelho** [comment]
I need a similar thing. Is there a way to not hide the button when user taps the button?
I didn't create an issue because I don't know if feature already exists or not
Thank you very much
