### ISSUE TITLE
Landscape blank space

### ISSUE THREAD

**Issue by trant** [MortimerGoro/MGSwipeTableCell#105]
When the cells are shown and the device is rotated to landscape there is this blank space, how can I reduce it? 

https://www.dropbox.com/s/bf2ww17gmpqht5a/empty_space_1.mov?dl=0

**Comment by trant** [comment]
When the rotation is finished I go through all the table view visible cells and call " [tableViewCell refreshButtons:NO];"

It fixed the issue

**Comment by edodiaz** [comment]
What worked for me using Autolayout was

`[tableView reloadData];
`
