### ISSUE TITLE
How to perform an action, when cell has reached its default position? (Swift)

### ISSUE THREAD

**Issue by MHX792** [MortimerGoro/MGSwipeTableCell#107]
Hi!

I would like to reload a tableView, after a button is pressed and the cell is back at its default position. Reloading the tableView before that cancels the slide back animation.

        let resetButton = MGSwipeButton(title: "Reset", backgroundColor: UIColor.grayColor(), callback: {( sender: MGSwipeTableCell!) -> Bool in
            self.tableView.reloadData()
            return true
        })

**Comment by MortimerGoro** [comment]
You can do it using a timer
```
let resetButton = MGSwipeButton(title: "Reset", backgroundColor: UIColor.grayColor(), callback: {( sender: MGSwipeTableCell!) -> Bool in
	let t = sender.leftSwipeSettings.animationTime;
	let delayTime = dispatch_time(DISPATCH_TIME_NOW,  Int64(t * Double(NSEC_PER_SEC)))
	dispatch_after(delayTime, dispatch_get_main_queue()) {
	    tableView.reloadData()
	}
})
```

Or toying with this delegate method:
```
-(void) swipeTableCell:(MGSwipeTableCell*) cell didChangeSwipeState:(MGSwipeState) state gestureIsActive:(BOOL) gestureIsActive;
```
