### ISSUE TITLE
Bug when changing the orientation of the device

### ISSUE THREAD

**Issue by nico75005** [MortimerGoro/MGSwipeTableCell#113]
There is a problem when changing the orientation of the device (from landscape to portrait or from portrait to landscape).

I work with auto layout. It goes back to normal once I tap somewhere.
![screen shot 2015-07-14 at 10 35 02](https://cloud.githubusercontent.com/assets/1647328/8663948/3f77f5a6-2a14-11e5-9603-eb98ce3a72c8.png)
![screen shot 2015-07-14 at 10 35 13](https://cloud.githubusercontent.com/assets/1647328/8663949/3f79cc14-2a14-11e5-9e11-86504c3ccabf.png)

**Comment by MortimerGoro** [comment]
Fixed in develop branch. I Will merge to master & CocoaPods in the next release.

**Comment by MortimerGoro** [comment]
Fixed in 1.5.1
