### ISSUE TITLE
Buttons appear underneath cell separator

### ISSUE THREAD

**Issue by rtconner11** [MortimerGoro/MGSwipeTableCell#114]
When swiping open the cell, the buttons appear underneath the cell's separator. With the native swipe to delete functionality, the row action buttons appear to be laid over the cell separator. Has anyone found how to achieve this effect or even noticed this?

<img width="89" alt="screen shot 2015-07-14 at 11 46 42 am" src="https://cloud.githubusercontent.com/assets/4603426/8679069/0d85d630-2a1e-11e5-9600-5fd2f8e05540.png">

**Comment by MortimerGoro** [comment]
You should be able to  fix that setting a higher zPosition to the button's layer or to the contentView's layer.

Try this
```
cell.contentView.layer.zPosition = 500;
```
Or this:
```
button.layer.zPosition = 500;
```

**Comment by rtconner11** [comment]
That worked! Thanks!

**Comment by winkelsdorf** [comment]
Great find 👍
