### ISSUE TITLE
Would like to detect when cell becomes fully expanded.

### ISSUE THREAD

**Issue by peterlondon1** [MortimerGoro/MGSwipeTableCell#117]
I'm using a cell that is expandable.

I'd like to change the text of a button when the cell has fully expanded.

I've looked at:

func swipeTableCell(cell: MGSwipeTableCell!, didChangeSwipeState state: MGSwipeState, gestureIsActive: Bool)

but it only seems to be called at the beginning of the cell expansion.
I can't use a timer because the user may swipe a small way along before doing the action to expand the cell.

Any suggestions gratefully accepted.

**Comment by peterlondon1** [comment]
I'm using a cell that is expandable.

I'd like to change the text of a button when the cell has fully expanded.

I've looked at:     func swipeTableCell(cell: MGSwipeTableCell!, didChangeSwipeState state: MGSwipeState, gestureIsActive: Bool) {


but it only seems to be called at the beginning of the cell expansion.
I can't use a timer because the user may swipe a small way along before doing the action to expand the cell.

Any suggestions gratefully accepted.

**Comment by MortimerGoro** [comment]
Hello, you can override the following method in your MGSwipeTableCell subclass:
```
-(void) setSwipeOffset:(CGFloat)offset
{
    [super setSwipeOffset:offset];
    if (!self.leftButtons.count) {
        return;
    }
    UIButton * button = [self.leftButtons objectAtIndex:0];
    NSString * text = @"Delete";
    if (offset > self.bounds.size.width * 0.8) {
        text = @"Yehaa";
    }
    if (button.titleLabel.text != text) {
        button.titleLabel.text = text;
    }
}
```

**Comment by peterlondon1** [comment]
Many thanks - will give it a try.

**Comment by peterlondon1** [comment]
Thanks, that worked!
