### ISSUE TITLE
isSwipeGestureActive seems to not be working in my case

### ISSUE THREAD

**Issue by nico75005** [MortimerGoro/MGSwipeTableCell#123]
I want to avoid presenting a view controller when I press a cell when another cell has a swipe gesture active.

So I have `swipeTableCell:shouldHideSwipeOnTap:` returns `false` and in my cell class, I override ` touchesBegan:withEvent:`. I loop through all the visible cells of my tableView and stop if there is one with `isSwipeGestureActive` set to `true`. If it's the case I stop and manually hide the swipe, if not, I call the `touchesBegan:withEvent:` from the super view.

But when I loop through the visible cell of my tableView, none of them have `isSwipeGestureActive` set to `true`.

------

I don't really know Objective-c but if I'm not wrong you check wether or not it's active by checking `_panRecognizer.state == UIGestureRecognizerStateBegan || _panRecognizer.state == UIGestureRecognizerStateChanged` but after every swipe, the gesture finishes by `UIGestureRecognizerStateEnded` and then goes back to the possible state.

**Comment by MortimerGoro** [comment]
isSwipeGestureActive means that the user is currently swiping (touching the cell). When the user finishes the gesture, the cell can be keep swiped but the isGestureActive is set to false because the user is not touching the cell.

If you want to check if a cell is swiped you can do this:
```
BOOL isSwiped = cell.swipeOffset != 0
```
