### ISSUE TITLE
How to reload specific cell when swipeable buttons are already dispalyed?

### ISSUE THREAD

**Issue by justme1** [MortimerGoro/MGSwipeTableCell#124]
Hi,

How can I reload specific cells while maintaining the same state the cell was in?

The right way is to use `reloadRowsAtIndexPaths` however if the cell was previously swiped and is currently showing the buttons you can choose, after calling to `reloadRowsAtIndexPaths` the buttons disappear so user needs to re-swipe the cell in order to see the buttons.

This can occur every 2 seconds so I must  control the cell so it will remember if it was opened and keep its state the same.

Also, if the reload is occurring during swiping of the cell, the swipe is canceled and the cell is displayed in closed state.

Can this be achieved?

Currently the way I solve this issue is  by observing the changes inside the cell and updating the cell's state from the cell observing method(via NSNotificationCenter). This is not ideal as it's not elegant that the cell is observing changes and updating itself. I'd much prefer to let the ViewController handle this.

Another way is to get the cell via the table view `cellForItem` method, and calling an update method on the cell, without calling   `reloadRowsAtIndexPaths`, something like this: http://stackoverflow.com/a/28048809/314848

What do you think?

Thanks

**Comment by MortimerGoro** [comment]
Hi,

I would implement that requirement using the cellForItem and custom update method instead of reloadRowsAtIndexPaths. Specially because a cell reload destroys the current swipe gesture. 

You can do something like this:

````
    MGSwipeTableCell * cell = [_tableView cellForRowAtIndexPath:indexPath];
    [cell update]; //Custom method to update your UIViews
    [cell refreshContentView]; //Refresh changes while swiping
```

**Comment by justme1** [comment]
This is exactly what we did. Thanks for the reply!
