### ISSUE TITLE
Support Carthage

### ISSUE THREAD

**Issue by danishin** [MortimerGoro/MGSwipeTableCell#127]
[Carthage](https://github.com/Carthage/Carthage) is another cool dependency manager. Personally, I like it much more than cocoapods for it being way less intrusive and modular. Could you add support for carthage?

[Integration](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework) seems pretty straightforward.

Thanks!

**Comment by kyledecot** [comment]
+1 I'd really like to see this added!

**Comment by apocolipse** [comment]
+1
