### ISSUE TITLE
iOS 9 Right-to-Left Layouts isn't working

### ISSUE THREAD

**Issue by hashier** [MortimerGoro/MGSwipeTableCell#129]
If I swipe on a table cell it doesn't swipe out far enough to see the whole action.

**Comment by MortimerGoro** [comment]
Can't reproduce. The project demos work fine on iOS 9

**Comment by hashier** [comment]
I tested as well (RightToLeft) and worked with demo-demo project. I had slight glitches with the Spotify-demo project.

Closing the ticket.

**Comment by waelsaad** [comment]
This issue might be related to the problem I am experiencing as described here:

https://github.com/MortimerGoro/MGSwipeTableCell/issues/168
