### ISSUE TITLE
Can't change swipeBackgroundColor once it is set

### ISSUE THREAD

**Issue by MichaelTzach** [MortimerGoro/MGSwipeTableCell#136]
I am going for a UI experience where the background is the same color as the button and the background could change without reinitializing the cell.

This can be fixed by adding a setter to the cell.

-(void)setSwipeBackgroundColor:(UIColor *)swipeBackgroundColor {
    _swipeBackgroundColor = swipeBackgroundColor;
    _swipeOverlay.backgroundColor = swipeBackgroundColor;
}

**Comment by MortimerGoro** [comment]
Fixed it 1.5.2
