### ISSUE TITLE
CocoaPod Support

### ISSUE THREAD

**Issue by rmsutton** [MortimerGoro/MGSwipeTableCell#137]
Is there any way to add CocoaPod support?

**Comment by julianwyz** [comment]
I used 
```pod "MGSwipeTableCell"``` 
And it seems to work fine.
Hope this helps!

**Comment by andrewhavens** [comment]
As julianwyz mentioned. This library already supports CocoaPods. Simply add this to your Podfile:

    pod "MGSwipeTableCell"
