### ISSUE TITLE
Button padding

### ISSUE THREAD

**Issue by robjkc** [MortimerGoro/MGSwipeTableCell#14]
One more small issue, I created my swipe buttons like below, but noticed that there was very little space around the text when displayed on screen.
[MGSwipeButton buttonWithTitle:@"Trash" backgroundColor:[UIColor redColor]];
[MGSwipeButton buttonWithTitle:@"More" backgroundColor:[UIColor lightGrayColor]];

To get around this I added spaces to one of the titles like so which caused both the Trash and More button widths to expand:
[MGSwipeButton buttonWithTitle:@" Trash " backgroundColor:[UIColor redColor]];

Is there a way you could implement a default padding similar to how Apple and components like MSCMoreOptionTableView display so I can avoid doing this myself?

Looking forward to adding this to my app so I can add right swipe as well. Thanks!

**Comment by jignesh133** [comment]
![screen shot 2017-11-03 at 12 10 13 pm](https://user-images.githubusercontent.com/3625744/32362527-0a6e20b4-c090-11e7-9f5e-47244cfe6a5f.png)

Hi. @MortimerGoro 

i have to make the cell like attached the image add some space before the Swipe Button. how can i achive like this.

Thanks in advance,
