### ISSUE TITLE
Swipe works on initial load, but after cells are reused, it doesn't work

### ISSUE THREAD

**Issue by julianwyz** [MortimerGoro/MGSwipeTableCell#142]
Everything works as expected until I scroll down enough so that iOS reuses the cells. After they are reused I can't swipe to reveal the buttons (as if there are no buttons attached). Even cells that worked initially, don't after being reused.

Any help would be awesome!

Also, after browsing around, it seems that there is something (possibly) quirky with subclassing MGSwipeTableCell(?). It may be unrelated, but I am subclassing MGSwipeTableCell into MyTableViewCell and using MyTableViewCell on my table.

Thanks!

Using iOS 9.0
Simulator and Device

**Comment by dxclancy** [comment]
I'm assuming it is your issue and not the libraries, which may be wrong.

It is difficult to help you without your source code.

The behavior your are seeing could be due to how you setup your cell in your cellForRowAtIndexPath method.  A typical mistake is to only do certain setup steps when a cell is created, but not when it is reused.

Do you do all the same setup regardless of the source of the cell?

**Comment by julianwyz** [comment]
I haven't used the library before, so it is a bit new to me.

I originally was assigning the rightButtons property to my cell in the cellForRowAtIndexPath

If the cell is reused it would still have the rightButtons assigned. This is what I had:
```
MyTableCell *cell = (MyTableCell*)[tableView dequeueReusableCellWithIdentifier:identifier];

if (!cell)
{
   cell = [[MyTableCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:identifier];
}
...
...
// configure the cell
...

cell.rightButtons = @[rightButton];
return cell;
```

After that didn't work I was looking at the Spotify Demo project and instead implemented the Delegate functions:
``-(NSArray*)swipeTableCell:(MGSwipeTableCell *)cell
 swipeButtonsForDirection:(MGSwipeDirection)direction
            swipeSettings:(MGSwipeSettings *)swipeSettings
        expansionSettings:(MGSwipeExpansionSettings *)expansionSettings```


```-(BOOL)swipeTableCell:(MGSwipeTableCell *)cell canSwipe:(MGSwipeDirection)direction fromPoint:(CGPoint)point```


```-(void) swipeTableCell:(MGSwipeTableCell*) cell didChangeSwipeState:(MGSwipeState)state gestureIsActive:(BOOL)gestureIsActive```

and in my cellForRowAtIndexPath I set the ```cell.delegate = self``` (Of course I also added the MGSwipeTableCellDelegate in my .h) and still after I scroll down enough so that the cells are reused, they don't have the swipe buttons.

Thanks for your help, if there is any more information I should provide, please let me know!

**Comment by julianwyz** [comment]
I'm not sure how, but a ```pod update``` and ``pod install``` seemed to have fixed this. I'll close this ticket. 

Thanks, all!

**Comment by khunshan** [comment]
is it resolved?

**Comment by julianwyz** [comment]
This is resolved. Forgive me, this issue was from a while ago, so I can't remember off the top of my head _exactly_ what I did to fix this, but I _do_ remember it was a mistake on my side and not the library's.
