### ISSUE TITLE
How to set the background color of a swipe to be a gradient?

### ISSUE THREAD

**Issue by andrewhavens** [MortimerGoro/MGSwipeTableCell#147]
I need to set the background of a swipe to be a gradient. As far as I can tell, the current API expects you to pass a solid color.

```objective-c
cell.leftButtons = @[[MGSwipeButton buttonWithTitle:@"" icon:[UIImage imageNamed:@"check.png"] backgroundColor:[UIColor greenColor]],
                          [MGSwipeButton buttonWithTitle:@"" icon:[UIImage imageNamed:@"fav.png"] backgroundColor:[UIColor blueColor]]];
```    

In order to generate a gradient, you need to apply a gradient layer to a view like this:

```objective-c
CAGradientLayer *gradient = [CAGradientLayer layer];
gradient.frame = view.frame;
gradient.colors = [NSArray arrayWithObjects:(id)[[UIColor whiteColor] CGColor], (id)[[UIColor blackColor] CGColor], nil];
[view.layer insertSublayer:gradient atIndex:0];
```

Is there a way that I can access the view that is used for applying the background color to apply my gradient?

**Comment by himanshujoshi47** [comment]
After initializing the button, you can set the custom gradient layer for `MGSwipeButton`, before adding it to `rightButtons` or `leftButtons` array.
