### ISSUE TITLE
How to force the swipes button to reload every time swipe the cell

### ISSUE THREAD

**Issue by JoeShi** [MortimerGoro/MGSwipeTableCell#152]
In my case, the swipe button should be different every time swipe the cell. 

For example, I swipe and tap the button to mark the item as my favourite, and swipe again and tap again to mark the item as NOT my favourite.  The favourite (and unfavourite ) button should appear different. 

The delegate method 
```
func swipeTableCell(cell: MGSwipeTableCell!, swipeButtonsForDirection direction: MGSwipeDirection, swipeSettings: MGSwipeSettings!, expansionSettings: MGSwipeExpansionSettings!) -> [AnyObject]! {
```
dose not get executed twice. 

How can I deal with this?

**Comment by MortimerGoro** [comment]
Hello,

Check the MailApp demo. The left to right swipe button changes text between 'Mark as read' and 'Mark as unread'. You can use the same wasy to customize your button. Here is the code snippet, you can access the specific button using cell.leftButtons or cell.rightButton arrays

        return @[[MGSwipeButton buttonWithTitle:[me readButtonText:mail.read] backgroundColor:[UIColor colorWithRed:0 green:122/255.0 blue:1.0 alpha:1.0] padding:5 callback:^BOOL(MGSwipeTableCell *sender) {
            
            MailData * mail = [me mailForIndexPath:[me.tableView indexPathForCell:sender]];
            mail.read = !mail.read;
            [me updateCellIndicactor:mail cell:(MailTableCell*)sender];
            [cell refreshContentView]; //needed to refresh cell contents while swipping
            
            //change button text
            [(UIButton*)[cell.leftButtons objectAtIndex:0] setTitle:[me readButtonText:mail.read] forState:UIControlStateNormal];
            
            return YES;
        }]];

**Comment by JoeShi** [comment]
@MortimerGoro Thank you, I got it. I need to call `cell.refreshContentView`.
