### ISSUE TITLE
Choose which button expand

### ISSUE THREAD

**Issue by gio00** [MortimerGoro/MGSwipeTableCell#157]
I have two right buttons, on swipe the first button from left fill all the cell. How can I make the last button instead, fill all the cell and trigger the action?

**Comment by MortimerGoro** [comment]
You can choose which button expand setting buttonIndex property of the MGSwipeExpansionSettings

**Comment by gio00** [comment]
It worked! thank you. I just set it to zero `expansionSettings.buttonIndex = 0`
