### ISSUE TITLE
Delegate call multiple time on single touch on iOS 9

### ISSUE THREAD

**Issue by hagile** [MortimerGoro/MGSwipeTableCell#162]
`- (BOOL) swipeTableCell:(MGSwipeTableCell*)cell tappedButtonAtIndex:(NSInteger)index direction:(MGSwipeDirection)direction fromExpansion:(BOOL)fromExpansion`

delegate calls multiple time.

*This is working fine under iOS 7-8*

**Comment by MortimerGoro** [comment]
Fixed in 353902c. I will be available in 1.5.2 release

**Comment by hagile** [comment]
@MortimerGoro, thanks for the quick response but it still not resolved.

**Comment by hagile** [comment]
Please let me know if you want a sample to reproduce this issue.

**Comment by hagile** [comment]
A simple workout for this is to recreate buttons everytime !! :(

**Comment by MortimerGoro** [comment]
Yes, please send me a sample to reproduce the issue. I can't reproduce with the demos.

**Comment by Ying1986** [comment]
Please swipe cell without click, and click swipe buttons several times.

**Comment by MortimerGoro** [comment]
It should be fixed in 1.5.3, I remove all the previous buttonClicked selectors now when the new selector is added.

**Comment by BasThomas** [comment]
Seems to be fixed in `1.5.3` indeed :+1:

**Comment by GalinaCode** [comment]
I'm using MGSwipeTableCell (1.5.4)
But still did not fixed this issue.

**Comment by GalinaCode** [comment]
@MortimerGoro 
I fixed this bug.
https://cloudup.com/cKjff_GSldv

**Comment by MortimerGoro** [comment]
Just fixed it in 1.5.5

Let me know if it works

**Comment by GalinaCode** [comment]
@MortimerGoro 
OK, It is working.
Thanks.
