### ISSUE TITLE
I can't add padding to MGButton

### ISSUE THREAD

**Issue by Ying1986** [MortimerGoro/MGSwipeTableCell#171]
I need to added bottom padding to MGSwipeButton.h

Can you added padding to MGButton when it has background?

![bottompadding](https://cloud.githubusercontent.com/assets/6648212/11578167/af1bfe70-9a2b-11e5-8376-f45b46beed94.png)

**Comment by MortimerGoro** [comment]
I have added topMargin and bottomMargin properties in the new release 1.5.4. Set a bottomMargin value to fix your padding in the image ;)
