### ISSUE TITLE
Handle errors with assets

### ISSUE THREAD

**Issue by josmanperez** [MortimerGoro/MGSwipeTableCell#174]
Hi! First of all, congratulations for this useful library, it's really a good work.

I've been searching on the docs if there is a option in the handler to catch whether or not a certain image haven't been downloaded, and if not load an default image. I know kingfisher is not made for assets files, but how can I detect if there is an error on the download

Thank you

**Comment by MortimerGoro** [comment]
Hi, I don't understand the issue. I think that this is for kingfisher, not for this library
