### ISSUE TITLE
subclass MGSwipeTableCell with autoLayout problem

### ISSUE THREAD

**Issue by anxiaoyi** [MortimerGoro/MGSwipeTableCell#178]
<img width="312" alt="screen shot 2016-02-15 at 2 11 24 pm" src="https://cloud.githubusercontent.com/assets/4382796/13041006/31306a30-d3ee-11e5-9798-88e8336b2dc1.png">

How to solve this problem

**Comment by anxiaoyi** [comment]
The tableviewcell content still keep in it's origin positions

**Comment by anxiaoyi** [comment]
I custom MGSwipeTableCell class, by using NSLayoutConstraint to control the subView's size and position, not directly using the Frame

**Comment by anxiaoyi** [comment]
I know the reason cause this problem ... should add subViews to the UITableViewCell.contentView

**Comment by MeGaPk** [comment]
@anxiaoyi i am idiot too :D. You are best!
