### ISSUE TITLE
Automatically reveal button as hint

### ISSUE THREAD

**Issue by bharatkrishna** [MortimerGoro/MGSwipeTableCell#184]
Is it possible to automatically show and hide the left or right buttons without the user swiping. This would be a hint to the user that those buttons are present. 

For example, in Amazon's app:

![revealshowhint](https://cloud.githubusercontent.com/assets/240429/13551651/5d0b55c2-e2f6-11e5-9cd4-8ced7a5e1194.gif)

**Comment by bharatkrishna** [comment]
Reading through the source code I found 2 undocumented functions 

```
func hideSwipeAnimated(animated: Bool)

func showSwipe(direction: MGSwipeDirection, animated: Bool)
```

Using these along with `dispatch_after` I could create the above effect. 

These functions should be documented to make it more helpful in using this great library.

**Comment by jerrygdm** [comment]
showSwipe called directly or with
 `    dispatch_async(dispatch_get_main_queue(), ^{
        [cell showSwipe:MGSwipeDirectionRightToLeft animated:YES];
    });
`
doesn't work. Any idea?

Thanks

**Comment by bharatkrishna** [comment]
Yes it works. I used `dispatch_after` to make it show and hide.

**Comment by jerrygdm** [comment]
If I try on your demo project this:

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
    MGSwipeTableCell * cell = [self tableView:tableView cellForRowAtIndexPath:indexPath];
        
    dispatch_async(dispatch_get_main_queue(), ^{
        [cell showSwipe:MGSwipeDirectionRightToLeft animated:YES];
    });
}

the cell doesn’t show buttons :(
Any idea? Thanks

**Comment by chessboy** [comment]
cell.setSwipeOffset(-150.0, animated: true, completion: nil) does a partial reveal

**Comment by goktugaral** [comment]
Any help?

**Comment by marchold** [comment]
This worked for me 
self.animationCell = cell;
            [self performBlock:^{
                dispatch_async(dispatch_get_main_queue(), ^{
                    [cell setSwipeOffset:-30
                                animated:YES
                              completion:^(BOOL finished) {
                                  if (finished) {
                                         [self performBlock:^{
                                             dispatch_async(dispatch_get_main_queue(), ^{
                                                 [self.animationCell setSwipeOffset:0];
                                            });
                                      } afterDelay:0.2];

                                  }
                              }];
                });
            } afterDelay:0.5];
