### ISSUE TITLE
Weird Animation when Insert or Deleting row 

### ISSUE THREAD

**Issue by Akhu** [MortimerGoro/MGSwipeTableCell#186]
I have weird animations issue using a MGSwipeTableCell cell subclass
A video worth thousand words : 
https://www.youtube.com/watch?v=HEOntyalik4&feature=youtu.be

By the way my cells are supposed to be twice as tall in storyboard, did MGSwipTableCell support autoresize cell from iOS8?

Thanks a lot

**Comment by MortimerGoro** [comment]
@Akhu I think that the problem is that the cell is trying to autohide expansion while the UITableView is running the delete/insert animation.

Try to return NO value in your click handler or tappedButtonAtIndex delegate method

**Comment by sergiodelamoshoptimix** [comment]
Thanks @MortimerGoro returning NO was exactly what I was looking for.

**Comment by Akhu** [comment]
Sorry for late response, returning "NO" didn't work for me, i had already tried before posting issue here.

The only thing that worked was to do this : 

(Calling this code inside `func swipeTableCell(cell: MGSwipeTableCell!, tappedButtonAtIndex index: Int, direction: MGSwipeDirection, fromExpansion: Bool) -> Bool`)

        CATransaction.begin(); //CATransaction allows me to know when the "moveRow" animation ends
        
        CATransaction.setCompletionBlock({ () -> Void in
            self.tableView.reloadData() //So I can call reloadData without breaking animation
        })

        self.tableView.beginUpdates()
        shoppingList.removeAtIndex(indexToMoveFrom.row)
        self.tableView.moveRowAtIndexPath(indexToMoveFrom, toIndexPath: NSIndexPath(forRow: cart.list_shopping_products.indexOf(shop)!, inSection: self.cartSectionId))
        self.tableView.endUpdates()
        
        CATransaction.commit()

I don't really know what was happened with animation but this "CATransaction" thing did the trick :)

I'm leaving this here if someone, someday have a similar issue

Thanks for help :+1:
