### ISSUE TITLE
control reaches end of non-void block

### ISSUE THREAD

**Issue by 008v** [MortimerGoro/MGSwipeTableCell#187]
MGSwipeButton *btn1 = [MGSwipeButton buttonWithTitle:nil backgroundColor:nil callback:^BOOL(MGSwipeTableCell *sender) {
            
            
 }];

**Comment by CavalcanteLeo** [comment]
im getting the same error

**Comment by CavalcanteLeo** [comment]
008v, why did you close this issue without giving any informations?

**Comment by CavalcanteLeo** [comment]
=(

**Comment by Insider77** [comment]
simply add `return YES`
