### ISSUE TITLE
Events duplicated again on 1.5.4 !!!

### ISSUE THREAD

**Issue by Ying1986** [MortimerGoro/MGSwipeTableCell#190]
https://github.com/MortimerGoro/MGSwipeTableCell/issues/160
https://github.com/MortimerGoro/MGSwipeTableCell/issues/162 were fixed in 1.5.3,

But it will appear again on 1.5.4.

https://github.com/MortimerGoro/MGSwipeTableCell/blob/c464019d9725b296d5700c72173baa6139085ffd/MGSwipeTableCell/MGSwipeTableCell.m#L96

It is valid statement???

@MortimerGoro 
Let me know when I can get the fixed version?

Thank you.

**Comment by MortimerGoro** [comment]
It should be fixed in 1.5.5

Let me know if it works
