### ISSUE TITLE
Use of [UIApplication sharedApplication] not allowed in App Extensions

### ISSUE THREAD

**Issue by emobtech** [MortimerGoro/MGSwipeTableCell#192]
Hi,

My app has an extension and because of the line below, I am not being able to use the latest version.

https://github.com/MortimerGoro/MGSwipeTableCell/blob/master/MGSwipeTableCell/MGSwipeTableCell.m#L643

Is it possible to change?

Thanks in advance.

Regards,

**Comment by mkramskoy** [comment]
Hi,

I have the same problem. I will be using a fork for now, but if you will find a good solution it will be great.

Thanks in advance

**Comment by MortimerGoro** [comment]
There isn't a builtin way to detect App Extension compilations in XCode. I have added the macro TARGET_IS_EXTENSION in this commit: 4df4d58ad148388212dac9081ad3d6ac6eff2b33

You can the define the macro in your project when compiling an App Extension. Yhis way yo don't need to use a fork 
1. Go to your project target build settings
2. Find (or search) Preprocessor Macros under Apple LLVM 6.0 - Preprocessing
3. Add TARGET_IS_EXTENSION in both the debug and release sections.

**Comment by pschneider** [comment]
Hi,

same issue seems to be in https://github.com/MortimerGoro/MGSwipeTableCell/blob/master/MGSwipeTableCell/MGSwipeButton.m#L97
