### ISSUE TITLE
Demo for Expansion in Swift?

### ISSUE THREAD

**Issue by mmasque** [MortimerGoro/MGSwipeTableCell#239]
I can't get expansion to work in Swift, a demo would be really useful.

**Comment by MortimerGoro** [comment]
I'm going to upload a swift demo very soon, in 1-2 days ;)

**Comment by MortimerGoro** [comment]
I've pushed 1.5.6 version with Swift interoperation imporvements. The swift 3.0 sample is ready too ;)
https://github.com/MortimerGoro/MGSwipeTableCell/tree/master/demo/MailAppDemoSwift

**Comment by mmasque** [comment]
Awesome, thank you!
