### ISSUE TITLE
Decrease title size, put image up to the title label.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [MortimerGoro/MGSwipeTableCell#249]
I want to decrease font size and put image over the text label.

**Comment by dimovskidamjan** [comment]
Hi @Rashesh-Bosamiya , you can use the `centerIconOverText` or `centerIconOverTextWithSpacing:` method to center the image above the title.

**Comment by Rashesh-Bosamiya** [comment]
Thank you, I will try this.
