### ISSUE TITLE
Dublicate cell content

### ISSUE THREAD

**Issue by Faisal0sal** [MortimerGoro/MGSwipeTableCell#250]
For some reason my cell when swiped will duplicate its content instead of moving it.
![screen shot 2016-11-06 at 17 24 22](https://cloud.githubusercontent.com/assets/10188948/20038498/022fbe06-a446-11e6-83b2-d9ea64d5e018.png)

**Comment by edwinfinch** [comment]
What was your solution to this?

**Comment by Faisal0sal** [comment]
@edwinfinch it was a long time ago but I think the solution was: when adding the cell content (labels. images etc) to the cell you're supposed to use `contentView.addSubview()` instead of `addSubview()`

**Comment by edwinfinch** [comment]
Sweet, thanks! It works.
