### ISSUE TITLE
Change the color of text leftSideButton and rightRightButton  

### ISSUE THREAD

**Issue by Prit-Singh** [MortimerGoro/MGSwipeTableCell#251]
Hi,
I need to change the color of text of leftButton and rightButton of cell and also change the font size of text of buttons,
Please let me know how to change the color of text. Its very urgent.

Thanks in advance.

**Comment by yukitoto** [comment]
```
let button = MGSwipeButton()
button.titleLabel # you can access to title label
```

**Comment by voxiadmin** [comment]
I know the issue is closed but this worked better for me, thanks:
```
let button = MGSwipeButton(title:"Title", backgroundColor: myUIColor)
    button.setTitleColor(myTitleUIColor, for: UIControl.State.normal)
```
