### ISSUE TITLE
_leftView / _rightView is null?

### ISSUE THREAD

**Issue by goktugaral** [MortimerGoro/MGSwipeTableCell#269]
Hello there,

I want show left or right buttons when the user click on the cell. For this, I'm using showSwipe method inside the didSelectRowAt method. But when I call the method, nothing was happened. When debug it;

UIView * buttonsView = direction == MGSwipeDirectionLeftToRight ? _leftView : _rightView;
On this line, buttonsView is nil because leftView and rightView is null.

What is the reason of it? What is it I'm doing wrong?

Thanks

**Comment by goktugaral** [comment]
Okey, for examination I have added

`cell.leftButtons = [MGSwipeButton(title: "Ok", icon: nil, backgroundColor: UIColor.blue)]
`

inside the didSelectRowAt method and I can see buttonsView has reference. So it is not nil and 
it is continue through

```
CGFloat s = direction == MGSwipeDirectionLeftToRight ? 1.0 : -1.0;
MGSwipeAnimation * animation = animated ? (direction == MGSwipeDirectionLeftToRight ? _leftSwipeSettings.showAnimation : _rightSwipeSettings.showAnimation) : nil;
[self setSwipeOffset:buttonsView.bounds.size.width * s animation:animation completion:completion];
```

But still nothing happened. I could not show button with programmatically.
Please help!

**Comment by MortimerGoro** [comment]
It works in the sample demos. For example open MailAppDemo project, and add this line into MailViewController.m

```
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
    MGSwipeTableCell * cell = [tableView cellForRowAtIndexPath:indexPath];
    [cell showSwipe:MGSwipeDirectionRightToLeft animated:YES];
}
```

**Comment by goktugaral** [comment]
@MortimerGoro Thank you so much, it works. I was trying on Swift and I guess I used dequeueReusableCell. 

```
func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
       let cell = tableView.cellForRow(at: indexPath) as! MGSwipeTableCell
        cell.leftButtons = [MGSwipeButton(title: "Ok", icon: nil, backgroundColor: UIColor.blue)]
        cell.showSwipe(.leftToRight, animated: true)  
    }
```
