### ISSUE TITLE
How can I get the index path of the table cell in the tappedButtonAt delegate method?

### ISSUE THREAD

**Issue by Sweeper777** [MortimerGoro/MGSwipeTableCell#279]
In this delegate method:

    func swipeTableCell(_ cell: MGSwipeTableCell, tappedButtonAt index: Int, direction: MGSwipeDirection, fromExpansion: Bool) -> Bool

I cannot get the index path of the cell whose button is tapped. I need the index path of the cell to access my model. I know I can put the action of the buttons in a closure when I create the buttons, but I think it's kind of messy to use closures and put complicated logic in them.

How can I get the index path of the cell?

**Comment by MortimerGoro** [comment]
You can get the indexPath using [tableView indexPathForCell:cell]

**Comment by Sweeper777** [comment]
Oh! I never knew that method existed! Thank you!

**Comment by gunhansancar** [comment]
Here is the Swift version. Incase anyone is interested
`guard let indexPath = tableView.indexPath(for: cell) else { return true }`
