### ISSUE TITLE
Force swipe on many cells => Actions not triggered

### ISSUE THREAD

**Issue by Aximem** [MortimerGoro/MGSwipeTableCell#282]
Hi, thanks for your job, really helpfull !

Btw if you force swipe on many cells : 
`
for index in 0..<myList.count {
    if let cell = self.tableView.cellForRow(at: IndexPath(row: index, section: 0)) as? MGSwipeTableCell {
        cell.showSwipe(MGSwipeDirection.rightToLeft, animated: true)
      }
 }
`

It displays all action buttons but then, if you click on a button, it will swipe back cells one by one.
And if you set shouldHideSwipeOnTap to false, no more actions are possible, buttons actions are not trigered anymore.
It seems buttons actions are trigered if and only if one cell is swipe.

Thanks

**Comment by MortimerGoro** [comment]
Have you tried to enable `allowsMultipleSwipe` on each cell?

**Comment by Aximem** [comment]
It works, Thanks @MortimerGoro
