### ISSUE TITLE
iOS 11 Crash

### ISSUE THREAD

**Issue by vanderhooft** [MortimerGoro/MGSwipeTableCell#294]
**Steps to reproduce:**
* using iOS 11 (15A5362a)
* show a table view which has MGSwipeTableCell(s) with MGSwipeButton
* swipe to display the MGSwipeButton
* pop the view controller

crashes here: https://github.com/MortimerGoro/MGSwipeTableCell/blob/d623fb9c4c75f6c5bf7307eff961cb96073b439c/MGSwipeTableCell/MGSwipeTableCell.m#L978 _objc[288]: Cannot form weak reference to instance (0x10212e200) of class UITableView. It is possible that this object was over-released, or is in the process of deallocation._

**More info:**
* also tested w/ iOS 10.2.1 which did not crash
* changing the reference from `__weak` to `__unsafe_unretained` seems to work (minimally tested.. but doesn't crash for me anymore)
idea from: https://stackoverflow.com/questions/10904990/10905056#10905056

**Comment by MortimerGoro** [comment]
Hi @vanderhooft 

Thank you very much for the detailed info about this crash, it was really helpful.

I decided to get rid of the _cachedParentTable reference. Using __unsafe_unretained seems a bit unsafe and may lead to other difficult to debug crashes. Doing the lookup is fast enough and it's only done in specific moments (when swipe starts or ends). So it's not vital to cache it.

**Comment by MortimerGoro** [comment]
I just published 1.6.1 release with this fix included

**Comment by vanderhooft** [comment]
Thanks for the update! Tested; works great.
