### ISSUE TITLE
Xcode 9 - Availability checks for Objective-C

### ISSUE THREAD

**Issue by sasojadrovski** [MortimerGoro/MGSwipeTableCell#297]
Hey @MortimerGoro,

Would it be possible to update the library to support the latest addition of Objective-C - availability checks? Would love to see the warnings that Xcode generates removed.

Looking forward to your feedback.

Cheers,
Sasho

**Comment by lee-jay** [comment]
The warnings are as below:
![5 pic](https://user-images.githubusercontent.com/15777039/31373667-8bea210e-adcd-11e7-97ec-82100c84f258.jpg)

**Comment by MortimerGoro** [comment]
Fixed in 1.6.2 ;)
