### ISSUE TITLE
Do I have to use the MGSwipeTableCell ? If i want to use my custom cell, how should i do?

### ISSUE THREAD

**Issue by wangyingbo** [MortimerGoro/MGSwipeTableCell#304]

**Comment by mrhaxic** [comment]
Yes, you can inherit the custom class from `MGSwipeTableCell`

**Comment by wangyingbo** [comment]
OK, thanks. I was just wondering if developers could use the category of MGSwipeTableCell, that will be more convenient!

**Comment by MortimerGoro** [comment]
This can be closed now, thanks for the reply mrhaxic
