### ISSUE TITLE
Unexpected '@' in program

### ISSUE THREAD

**Issue by kuldeep13990** [MortimerGoro/MGSwipeTableCell#305]
after updating pod, I am getting below error **Unexpected '@' in progress** in MGSwipeButton.m file.

how can I fix this?

**Comment by MortimerGoro** [comment]
The new version is using a XCode 9 feature (availability check syntax).

I have pushed a new 1.6.3 version to add backwards compatibility with XCode 8. Update the pod again and the issue should be fixed.

**Comment by MortimerGoro** [comment]
Update to 1.6.4 better, I missed a availability check in 1.6.3

**Comment by kuldeep13990** [comment]
@MortimerGoro , Thanks now it's working fine.
