### ISSUE TITLE
CornerRadius and other customization

### ISSUE THREAD

**Issue by SeRG1k17** [MortimerGoro/MGSwipeTableCell#307]
![simulator screen shot - iphone 7 - 2017-11-22 at 18 36 18](https://user-images.githubusercontent.com/13317173/33135691-28364486-cfb4-11e7-971e-41f0bdc3a0c2.png)

Is it possible to implement the following:
1) Hide the cornerRadius of the button, but keep it in its normal state.
I think I need to move the container or swipeView
2) == 1
3) make cornerRadius

**Other settings:**
![screen shot 2017-11-22 at 18 35 00](https://user-images.githubusercontent.com/13317173/33135704-3492045e-cfb4-11e7-80f8-09b2b97b5ce1.png)

**Constraints:**
subContentView: top and bottom = 8.0
subContenView: leading  = 16.0, trailing = 0.0
tableView: leading = 0.0, trailing = 16.0
//it`s hack for clips animation view

```swift
func swipeTableCell(_ cell: MGSwipeTableCell, swipeButtonsFor direction: MGSwipeDirection, swipeSettings: MGSwipeSettings, expansionSettings: MGSwipeExpansionSettings) -> [UIView]? {
//...
        expansionSettings.buttonIndex = 0
        expansionSettings.fillOnTrigger = true
        expansionSettings.threshold = 1.1
        
        swipeSettings.transition = .static
        swipeSettings.topMargin = coloredView.frame.origin.y
        swipeSettings.bottomMargin = (cell.bounds.height - coloredView.bounds.height) / 2
        swipeSettings.offset = notifCell.coloredViewTrailingConstraint.constant
//...
}
```

If this is not possible, then is it possible to do the following:

- Fill the empty space between the red button(delete) and the content with red color .
or 
- Limit the swipe with the end of the red button.

**Comment by SeRG1k17** [comment]
I found another solution. Close this, thank you.

**Comment by abadikaka** [comment]
How did u do this @SeRG1k17 ?
