### ISSUE TITLE
Unable to add MGSwipeTableCell via Swift Package

### ISSUE THREAD

**Issue by muh-bilal** [MortimerGoro/MGSwipeTableCell#360]
When I tried to install `MGSwipeTableCell` library via `Swift Package` I am getting following error:
 
<img width="728" alt="Error" src="https://user-images.githubusercontent.com/5365557/124673780-c75cdd00-deb9-11eb-92d9-a7f66484abb9.png">

**Comment by sainttail** [comment]
Try using revision and pull from latest commit instead, I saw that the tag version still does not contain `Package.swift` yet

**Comment by MortimerGoro** [comment]
Should be fixed in v1.6.14
