### ISSUE TITLE
Tag 1.6.11 does not include Swift Package Manager support.

### ISSUE THREAD

**Issue by inacioferrarini** [MortimerGoro/MGSwipeTableCell#362]
Hello there.

The last tag 1.6.11 (0ct 16, 2019) does not include Swift Package Manager support.

Would you be so kind to create a tag having Swift Package Manager support?

Best regards,

**Comment by MortimerGoro** [comment]
Hello, sorry for the delay.

The latest tag (1.6.14) includes the Swift Package Manager. Please reopen the issue if you encounter any problem, thanks.
