### ISSUE TITLE
Crash when using multiple MGSwipeButtons in Swift 

### ISSUE THREAD

**Issue by alangue** [MortimerGoro/MGSwipeTableCell#40]
Hello!
I am using iOS 8 and Swift.

When I create one MGSwipeButton, it works fine but I have an issue when I create two or more MGSwipeButtons. Here is my code:

let cell: CustomTableViewCell = tableView.dequeueReusableCellWithIdentifier(kCustomCellIdentifier, forIndexPath: indexPath) as CustomTableViewCell

cell.rightButtons = [[MGSwipeButton(title: "Button 1", backgroundColor: UIColor.blackColor())],[MGSwipeButton(title: "Button 2", backgroundColor: UIColor.redColor())]]

My CustomTableViewCell is a sub class of MGSwipeTableCell. My breakpoint stops in this method:

"MGSSwipeTableCell.m"
-(instancetype) initWithButtons:(NSArray*) buttonsArray direction:(MGSwipeDirection) direction
{
    CGSize maxSize = CGSizeZero;
    for (UIView \* button in buttonsArray) {
        maxSize.width = MAX(maxSize.width, button.bounds.size.width); // breakpoint here
        maxSize.height = MAX(maxSize.height, button.bounds.size.height);
    }
    [...]
}

And I have this message :
2014-11-18 10:41:34.828 MyProject[13183:2530873] -[Swift._NSSwiftArrayImpl bounds]: unrecognized selector sent to instance 0x7fd8faeab890
2014-11-18 10:56:09.548 MyProject[13183:2530873] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[Swift._NSSwiftArrayImpl bounds]: unrecognized selector sent to instance 0x7fd8faeab890'

Thank you for your help! :)

**Comment by Samir-Shaikh** [comment]
It works perfectly..
