### ISSUE TITLE
Two Cell Can Swipe simultaneously 

### ISSUE THREAD

**Issue by nikhildcodalsystem** [MortimerGoro/MGSwipeTableCell#43]
Hey I want to stop two cell swiping simultaneously?

**Comment by MortimerGoro** [comment]
Fixed ;)

**Comment by imsg** [comment]
Glad to see this fix but per my testing this issue cannot be fixed completely. 
I can still repro this issue sometimes.

**Comment by avg151** [comment]
Hello. This problem is repeated at me as well. If you open a menu of two cells with a small interval of time, no such problem. But if you pull the two cells at the same time, the problem persists. Is it possible to solve?

**Comment by AYastrebov** [comment]
The same issue. I still can swipe two cells at the same time
