### ISSUE TITLE
When sliding, cell has white background

### ISSUE THREAD

**Issue by lfarah** [MortimerGoro/MGSwipeTableCell#47]
My cell has a blue background, but when I slide, it turns into white

**Comment by MortimerGoro** [comment]
I can't reproduce the issue. I have tested the MailApp demo, setting a UIColor.blueColor to a cell.backgroundColor or to a cell.contentView.backgroundColor and the color remains blue while swiping. Can you send me a testcase?

**Comment by erkanyildiz** [comment]
Encountered the same issue. 
It happens when cell.backgroundColor is set to UIColor.clearColor.

**Comment by lfarah** [comment]
I fixed the issue by changing the last line from [UIColor whiteColor] to [UIColor clearColor]
    

    -(UIColor *) backgroundColorForSwipe
    {
    if (_swipeBackgroundColor) {
        return _swipeBackgroundColor; //user defined color
    }
    else if (self.contentView.backgroundColor && ![self.contentView.backgroundColor isEqual:[UIColor clearColor]]) {
        return self.contentView.backgroundColor;
    }
    else if (self.backgroundColor && ![self.backgroundColor isEqual:[UIColor clearColor]]) {
        return self.backgroundColor;
    }
    return [UIColor clearColor];
    }

**Comment by MortimerGoro** [comment]
Fixed. Thanks for the pull request.
