### ISSUE TITLE
Is MGSwipeTableCell safe on arm64 platform ?

### ISSUE THREAD

**Issue by cuichunjian** [MortimerGoro/MGSwipeTableCell#49]
you know, apple will reject any app that doesn't support arm64 after next Feb. That means all third-party frameworks in my project need support arm64. MGSwipeTableCell is a good framework, so is it safe on arm64 platform ?

**Comment by MortimerGoro** [comment]
Yes, MGSwipeTableCell is totally compatible with arm64. I have published some apps using this component with arm64 arch included.
