### ISSUE TITLE
Subclassing MGSwipeTableCell

### ISSUE THREAD

**Issue by plaetzchen** [MortimerGoro/MGSwipeTableCell#5]
Hi,

I am trying to use MGSwipeCell in a storyboard based app. I subclassed my table cell views for using custom IBOutlets. Now I changed the Superclass of those classes to "MGSwipeTableCell" and added two left buttons to the cell but I simple can't get the buttons to show up. Do I need to change something in my sub-classes?

Thank you for your work!

Philip

**Comment by scorpionking2k5** [comment]
Using a subclass with a nib.
Tried using with and without delegate. 
Delegate methods get called but nothing happening still. Failing to get any swipe action at all.

Tried all the solutions mentioned above. Nothing still working.

**Comment by jaisongreen** [comment]
I am having the same issue as scorpionking2k5.

Subclassing with a XIB, delegate methods get called but swipe buttons dont show up at all.

**Comment by Errortype520** [comment]
Still an issue using Swift 2, and Xcode 7. Cells do not swipe. Loading cell from XIB.

**Comment by oyalhi** [comment]
I have exactly the same problem. Swipe fails to work when loading the cell from xib; otherwise it works fine.

**Comment by siralam** [comment]
Reporting same problem as above.

The way I do this is:

In ViewController:

```swift
        tableView.register(CustomTableCell.self, forCellReuseIdentifier: "RollableItem")
        tableView.dataSource = self
        tableView.delegate = self
```

CustomTableCell.swift:

```swift
class CustomTableCell: MGSwipeTableCell {
    
    @IBOutlet var rootView: UIView!
    @IBOutlet weak var itemName: UILabel!
    @IBOutlet weak var itemRating: UILabel!
    @IBOutlet weak var itemSwitch: UISwitch!
    
    required override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        commonInit()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        commonInit()
    }
    
    private func commonInit () {
        Bundle.main.loadNibNamed("CustomTableCell", owner: self, options: nil)
        addSubview(rootView)
        rootView.frame = self.bounds
        rootView.autoresizingMask = [.flexibleHeight, .flexibleWidth]
    }
    
}
```

**Comment by richardlevy** [comment]
This is happening for me.  I just migrated a cell from storyboard to a XIB to make it reusable and swipes don't work.  I can see that it receives pan gestures OK and is setting offsets but nothing appears on the screen.  I've got super calls to awakeFromNib, and initWithDecoder but nothing ever gets displayed.

I've even tried calling the interval initViews later in the lifecycle to see if that helps and it doesn't.

I've updated to the latest source too.

Still, nothing.  

Did anyone crack this?

**Comment by richardlevy** [comment]
I cracked this!

It was my fault of course.  In the XIB, which I had created separately from the class, I had created my layout inside the default view (which was a UIView).  I should have dragged a UITableViewCell in and created my view with that.  

Once I did that it worked fine!
