### ISSUE TITLE
Not able to swipe to reveal right after scrolling collection view children of cell content view

### ISSUE THREAD

**Issue by lovesharyn** [MortimerGoro/MGSwipeTableCell#50]
Hi,

I have attached a project to reproduce the issue.

When a collection view is added to the cell content view, the first swipe is working fine when we are not touching the collection view.

Once we attempt to scroll on the collection view, somehow the touches are messed up and we are not able to swipe to reveal right buttons anymore.

Please run the demo of the following repo for more details.
https://github.com/lovesharyn/MGSwipeTableCellCollectionViewTest

Thank you for your time.

**Comment by MortimerGoro** [comment]
Fixed ;) Thank you for the testcase.
