### ISSUE TITLE
Starting swiping on one cell while another one is open makes the swipe a no-op

### ISSUE THREAD

**Issue by blixt** [MortimerGoro/MGSwipeTableCell#51]
1. Show the MGSwipeButtons for a cell
2. Try to show the buttons for another cell further down the table view
3. Note that all that happens is that the first cell closes but nothing happens with the cell you swiped

Maybe there is a good reason for this but in my own testing I found that the UI felt weird when I was trying to open up different menus for different rows (e.g., I swiped the wrong row and want to swipe open the one below). Having to close the one that's open before you can open another one feels like a bit of extra work.

Is this configurable? Could it be?

**Comment by MortimerGoro** [comment]
Hi Blixt,

The iOS 8 Mail App works the same way, you have to close the swiped cell to swipe another one. It could be a good feature to make this behavior configurable, I'll take a look ;)

**Comment by stephsharp** [comment]
+1 - I'm looking for this functionality too.

**Comment by stephsharp** [comment]
I've implemented this functionality with a property called `autoHideOnSwipe`. I haven't tested it thoroughly yet but it appears to be working pretty well. See here: f273d0021d289a32a71e7e5ea927690b48a96c60

Steph

**Comment by MortimerGoro** [comment]
Fixed
