### ISSUE TITLE
fillOnTrigger and "flash" before removal of cell

### ISSUE THREAD

**Issue by Nemesisprime** [MortimerGoro/MGSwipeTableCell#52]
On the demos and when implemented, there is a flash of the cell in its default state before the cell is handled when fillOnTrigger is set. 

Is there anyway to keep the cell filled until it is updated or removed?

**Comment by MortimerGoro** [comment]
Hi Nemesisprime,

I have fixed the flash when a cell is removed. You have to return NO in the button callback or tappedButtonAtIndex delegate to avoid cell autoHide. See the updated demos.

**Comment by Nemesisprime** [comment]
Thanks!
