### ISSUE TITLE
Pressing a UITableViewCell when a cell is currently swiped open

### ISSUE THREAD

**Issue by kekearif** [MortimerGoro/MGSwipeTableCell#53]
Hi, I am using MGSwipeTableCell in my app. When a cell is swiped open to reveal buttons if I tap on another cell it dismisses the swipe cell (hides the buttons again). I want the previously swiped cell to dismiss the buttons and then select the new cell in one tap instead of two (i.e. tap off and then tap new cell). Is there any way to to do this?

thanks

**Comment by stephsharp** [comment]
Sounds like you want the same feature mentioned here: #51

My implementation of this functionality is here: f273d0021d289a32a71e7e5ea927690b48a96c60
You just need to set `cell.autoHideOnSwipe = YES` and it should work as expected :grinning:

**Comment by MortimerGoro** [comment]
Fixed
