### ISSUE TITLE
cell doesn't display selection state when swipe is closed

### ISSUE THREAD

**Issue by frahar** [MortimerGoro/MGSwipeTableCell#56]
Can be reproduced in the enclosed email app demo:
1) select a cell
2) use swipe (doesn't matter if left or right)
3) close swipe
Result: cell isn't displayed as selected anymore. If you scroll the cell out of the visible table area and back in, it is selected again

btw: great library. many thanks to the author!

**Comment by MortimerGoro** [comment]
Fixed

**Comment by dbarchmann** [comment]
Same problem with the actual version. After expansion cell is not displayed as selected anymore. After scrolling out and in it is shown as selected again. This only happens when .fillOnTrigger is set to true. Any ideas?
