### ISSUE TITLE
Table input overlay isn't removed when cell is deleted

### ISSUE THREAD

**Issue by annca** [MortimerGoro/MGSwipeTableCell#57]
There's an assumption that the following method will be called when a cell is deleted and therefore will hide the overlay.

```
-(void) willMoveToSuperview:(UIView *)newSuperview;
{
    if (newSuperview == nil) { //remove the table overlay when a cell is removed from the table
        [self hideSwipeOverlayIfNeeded];
    }
}
```

However, this doesn't necessarily seem to be the case. I delete a cell by calling
 `[self.tableView deleteRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationLeft];` 

yet the table overlay stays and it takes an extra tap to initiate the next action. Perhaps method `hideSwipeOverlayIfNeeded` could be exposed as public and called when needed?

**Comment by MortimerGoro** [comment]
Fixed
