### ISSUE TITLE
How can I swipe the only needed cell?

### ISSUE THREAD

**Issue by EvgenyKarkan** [MortimerGoro/MGSwipeTableCell#63]
Hey!
I need to implement such feature - to swipe only needed cell in my table view. (not every cell)
Please point me - how can I disable and enable swipe for needed cell?
I suggest - it will be possible by set the right or left buttons to nil.
But maybe there is a more clear way to do it?
Best wishes!

**Comment by mergesort** [comment]
`- (BOOL)swipeTableCell:(MGSwipeTableCell *)cell canSwipe:(MGSwipeDirection)direction tableView:(UITableView *)tableView;`

Just return `YES` for the cells that you want to swipe, and `NO` for the ones you don't want to swipe.

**Comment by EvgenyKarkan** [comment]
Thanks.
