### ISSUE TITLE
MGSwipeButton only triggers on first tableview row

### ISSUE THREAD

**Issue by sirhcmcd** [MortimerGoro/MGSwipeTableCell#65]
I only have 1 left cell button in my tableview, so I've opted initially for simple inline implementation, which does the expand fills and triggers MGSwipeButton only on the first tableview row, but not any subsequent rows.  Any ideas?  Should I use the delegate method instead?

**Comment by MortimerGoro** [comment]
Hi Chris, I can't reproduce the issue. I have tested the demo project with a single left button using inline callback instead of delegate and the expansions and trigger callbacks are ok.

Can you send me a testcase?

**Comment by sirhcmcd** [comment]
Ok figured it out...  to enable the expand fill for the cell, I need to specifically set the following line:

        cell.leftExpansion.buttonIndex = 0; 

I was a little confused with how the demo app cleverly set up the test data and after some debugging figured it out.
