### ISSUE TITLE
Cocoapod installation error

### ISSUE THREAD

**Issue by NitWitStudios** [MortimerGoro/MGSwipeTableCell#70]
Trying to install via cocoa pods and getting this error:
   
    [!] Unable to satisfy the following requirements:
    - `MGSwipeTableCell (= 1.3.6)` required by `Podfile`

Podfile looks like this:

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, "7.0"
    pod "MGSwipeTableCell", "1.3.6"
    ...other pods...

Don't have any problems with the other pods, just this one. Any suggestions?

**Comment by NitWitStudios** [comment]
Changed the version to 1.3.5 and it installed ok. But your pod spec has the version set to 1.3.6. Can you update?

**Comment by MortimerGoro** [comment]
I have just pushed 1.4.0 to cocoapod. Try with that version ;)

**Comment by NitWitStudios** [comment]
Cool, worked! Thanks for the prompt response and update! Cheers! :+1:
