### ISSUE TITLE
Getting indexPath.row for selected cell after clicking button

### ISSUE THREAD

**Issue by dhint4** [MortimerGoro/MGSwipeTableCell#74]
After looking through all the documentation, I can't seem to find how to get the indexPath.row property for the selected cell. Is this currently possible?

Thanks

**Comment by MortimerGoro** [comment]
The indexPath is not passed in the delegate but the cell itself, you have to use [tableView indexPathForCell:cell]

**Comment by walsh2000** [comment]
I'm using subclasses of MGSwipeTableCell, so I set a property on the cell at cellForIndexPath time.
