### ISSUE TITLE
Swiped cell state issue when table view is scrolling

### ISSUE THREAD

**Issue by imsg** [MortimerGoro/MGSwipeTableCell#76]
In an early version if a cell is swiped, the table view cannot be scrolled. 
But now table view can be scrolled if a cell is swiped. I don't know why we make this change. 

In this case this swiped cell will back to normal state if user scrolls the table view, but didChangeSwipeState delegate is not called. 
This issue can be reproduced in mail demo. 

Thanks so much.

**Comment by MortimerGoro** [comment]
Fixed in 1.4.1 ;)
