### ISSUE TITLE
"tappedButtonAtIndex" called twice...

### ISSUE THREAD

**Issue by idoodler** [MortimerGoro/MGSwipeTableCell#77]
Hi, I just updated to the latest version of MGSwipeTableCell, and I am facing an issue with 
```Objective-C
-(BOOL) swipeTableCell:(MGSwipeTableCell*) cell tappedButtonAtIndex:(NSInteger) index direction:(MGSwipeDirection)direction fromExpansion:(BOOL) fromExpansion {}
```
where the delegate function is called twice where it should be called once.

*For example:*

I swipe a cell and press on a button --> methode will be called once
**THEN** I swipe another cell and press on a button --> methode will be called one time with the parameters from before and the other with the new parameters

Any ideas?

**Comment by MortimerGoro** [comment]
Hi,

I can't reproduce this issue in the MailAppDemo and MGSwipeDemo projects. Can you give me more info or send me a testcase?

Thanks

**Comment by aliawais** [comment]
In MGSwipeCell.m
Add following line
[(UIButton *)button removeTarget:nil action:NULL forControlEvents:UIControlEventAllEvents];

before - line 80
[(UIButton *)button addTarget:self action:@selector(buttonClicked:) forControlEvents:UIControlEventTouchUpInside];

**Comment by mcicak** [comment]
@aliawais Thanks! That solved same problem in my app too.

**Comment by zielinskikamil** [comment]
Hello, 
recently I found similar issue with my app.
When user swiped and clicked button, click event was executed x+1 times. 

I fixed it changing flag for removing button events in method MGSwipeTableCell dealloc (line 89):

```objectivec
-(void) dealloc
{
    for (UIView * button in _buttons) {
        if ([button isKindOfClass:[UIButton class]]) {
            [(UIButton *)button removeTarget:self action:@selector(buttonClicked:) forControlEvents:UIControlEventAllEvents];
        }
    }
}
```
