### ISSUE TITLE
Swift problem with one enum

### ISSUE THREAD

**Issue by dhoerl** [MortimerGoro/MGSwipeTableCell#78]
MGSwipeTransition3D causes the whole enum to become unusable in Swift. I just posted on the Swift forum, the problem is that stripping off 'MGSwipeTransition' leaves the value starting with a number, which is illegal.

The suggestion was to change it to 'MGSwipeTransitionThreeD'.

**Comment by MortimerGoro** [comment]
Fixed in 1.4.1 ;)
