### ISSUE TITLE
Swift protocol prototypes

### ISSUE THREAD

**Issue by dhoerl** [MortimerGoro/MGSwipeTableCell#79]
If anyone is interested:

	func swipeTableCell(cell: MGSwipeTableCell!, canSwipe direction: MGSwipeDirection) -> Bool {
	}

	func swipeTableCell(cell: MGSwipeTableCell!, didChangeSwipeState state: MGSwipeState, gestureIsActive: Bool) {
	}
	
	func swipeTableCell(cell: MGSwipeTableCell!, tappedButtonAtIndex index: Int, direction: MGSwipeDirection, fromExpansion: Bool) -> Bool {
	}

**Comment by MortimerGoro** [comment]
I'll add a demo using Swift soon, so I close this 'issue'.

**Comment by ngergo100** [comment]
May I ask you where is that Swift demo? I would really appreciate it!

**Comment by dhoerl** [comment]
Really, with the delegate prototypes I posted, you can get this framework supported in Swift easily.

**Comment by mhauss** [comment]
I can't seem to implement the delegate methods in swift. They never seem to get called. Can you please post the demo / example?

**Comment by dfbrownstone** [comment]
here's a working example: (Swift 2.0, Xcode 7 beta 5)

override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
            
        let cell = tableView.dequeueReusableCellWithIdentifier("Cell", forIndexPath: indexPath) as! MGSwipeTableCell        
        var recipe:Recipe = myRecipes[indexPath.row]
.
.
.
    cell.delegate = self
   let delButton =  MGSwipeButton(title: "",  icon:UIImage(named:"trashcan",inBundle:NSBundle.mainBundle(),compatibleWithTraitCollection:nil), backgroundColor: UIColor.redColor())

    return cell
}

    // MARK: - MGSwipeTableCellDelegate
    
    func swipeTableCell(cell: MGSwipeTableCell!, canSwipe direction: MGSwipeDirection) -> Bool {
        return true
    }
    
    func swipeTableCell(cell: MGSwipeTableCell!, didChangeSwipeState state: MGSwipeState, gestureIsActive: Bool) {
    }
    
func swipeTableCell(cell: MGSwipeTableCell!, tappedButtonAtIndex index: Int, direction: MGSwipeDirection, fromExpansion: Bool) -> Bool {
        let indexPath = tableView.indexPathForCell(cell)
        var recipe:Recipe = myRecipes[indexPath!.row]
        let recipeToRemove = recipe as Recipe
        self.myRecipes.removeAtIndex(indexPath!.row)
        let managedContext = self.appDelegate.managedObjectContext
        managedContext.deleteObject(recipeToRemove)
        do {
                try managedContext.save()
        } catch {
                let nserror = error as NSError
                NSLog("Unresolved error \(nserror), \(nserror.userInfo)")
                abort()
        }
        tableView.deleteRowsAtIndexPaths([indexPath!], withRowAnimation: UITableViewRowAnimation.Fade)
       return true
}

**Comment by cs98-jon** [comment]
@mhauss If your delegate methods are not being called you most likely are not setting the delegate for the cell:
```
    override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCellWithIdentifier(cellIdentifier, forIndexPath: indexPath) as! MGSwipeTableCell
        cell.delegate = self
        ...
        return cell
    }
```

**Comment by RomeHein** [comment]
Where do I put these swift delegate method ?
