### ISSUE TITLE
Right button is clipped if UITableView has section index titles

### ISSUE THREAD

**Issue by subhashdaga** [MortimerGoro/MGSwipeTableCell#8]
Right most button is clipped if you override the following UITableViewDataSource delegate -
- (NSArray *)sectionIndexTitlesForTableView:(UITableView *)tableView;

Any suggestions how it can be fixed? Thanks!

**Comment by mmahkamov** [comment]
Faced the same issue. Took me some time to find about the offset property.

The offset property can be used like this to solve the issue with the section index titles:

```
- (NSArray *)swipeTableCell:(MGSwipeTableCell *)cell swipeButtonsForDirection:(MGSwipeDirection)direction swipeSettings:(MGSwipeSettings *)swipeSettings expansionSettings:(MGSwipeExpansionSettings *)expansionSettings {
    if (direction == MGSwipeDirectionRightToLeft) {
        // adjust the offset to the content width to account for the section index
        CGFloat offset = cell.frame.size.width - cell.contentView.frame.size.width;
        swipeSettings.offset = offset;

       ....
   }

   ...
}
```

There's no API to get the width of the section title index in iOS. However, the contentView of UITableViewCell is adjusted automatically not to overlap with the section title index. So you get the difference between the cell width and cell content width, then set it as the offset.

**Comment by ajbyrne** [comment]
Thanks. This works nicely.
