### ISSUE TITLE
How to activate swiping the cell when you swipe the buttons in the cell

### ISSUE THREAD

**Issue by waelsaad** [MortimerGoro/MGSwipeTableCell#80]
Hi, Forgive me if its a simple question but I am learning and I really like your component. 

I need your assistance with the following please:-

I am creating a MGSwipeTableCell that is full of buttons leaving no white empty space. I would like to be able to swipe the cell when I tap the buttons to swipe.  Thank you.

**Comment by MortimerGoro** [comment]
Hi, 

You can swipe a cell programmatically with this method:

[cell showSwipe: (MGSwipeDirection) direction animated: (BOOL) animated]

**Comment by waelsaad** [comment]
Thank you, I have this working now by adding a swipe gesture on the buttons then calling the showSwipe method but when hiding the cell programmatically that way the speed is not the same as when we are showing the buttons, its much faster. 

How do I use the showSwipe method or other methods so that I am hiding the buttons at the same speed as showing them as if I am dragging the buttons to be hidden back to its original state?.

I hope you know what I mean :). Thanks again.

**Comment by waelsaad** [comment]
In other words I would like to hide the buttons as I am dragging them back to the original state (hidden).

**Comment by Ji11erBug** [comment]
In the default mail app in iOS 8 its works by default. I think this functionality should be added.

**Comment by Ji11erBug** [comment]
I do not know whether this is the best solution. I am updated "fetchButtonsIfNeeded:" in the MGSwipeTableCell.m
```
-(void) fetchButtonsIfNeeded
{
    if (_leftButtons.count == 0 && _delegate && [_delegate respondsToSelector:@selector(swipeTableCell:swipeButtonsForDirection:swipeSettings:expansionSettings:)]) {
        _leftButtons = [_delegate swipeTableCell:self swipeButtonsForDirection:MGSwipeDirectionLeftToRight swipeSettings:_leftSwipeSettings expansionSettings:_leftExpansion];
        for (UIButton *button in _leftButtons) {
            UIPanGestureRecognizer *panRecognizer = [[UIPanGestureRecognizer alloc] initWithTarget:self action:@selector(panHandler:)];
            [button addGestureRecognizer:panRecognizer];
        }
    }
    if (_rightButtons.count == 0 && _delegate && [_delegate respondsToSelector:@selector(swipeTableCell:swipeButtonsForDirection:swipeSettings:expansionSettings:)]) {
        _rightButtons = [_delegate swipeTableCell:self swipeButtonsForDirection:MGSwipeDirectionRightToLeft swipeSettings:_rightSwipeSettings expansionSettings:_rightExpansion];
        for (UIButton *button in _rightButtons) {
            UIPanGestureRecognizer *panRecognizer = [[UIPanGestureRecognizer alloc] initWithTarget:self action:@selector(panHandler:)];
            [button addGestureRecognizer:panRecognizer];
        }
    }
}
```

**Comment by waelsaad** [comment]
Ji11erBug thats amazing. Thank you so much. This is a really great module.

**Comment by MortimerGoro** [comment]
I have added a new property  in 1.4.1 version that controls if swipping is enabled when tapping on swiped buttons. It's enabled by default.

**Comment by richadua** [comment]
How to restrict dragging of swipe tableviewell beyond the width of right buttons present?
