### ISSUE TITLE
fillOnTrigger not working properly with UITableViewCellAccessoryDisclosureIndicator

### ISSUE THREAD

**Issue by MuscleRumble** [MortimerGoro/MGSwipeTableCell#82]
This is what happens:

![fillontrigger-bug](https://cloud.githubusercontent.com/assets/2924160/7042762/7f82a85c-dde4-11e4-9042-aef36aa1248c.png)

The cell is not properly filled with the action button (I swiped from right to left). I can still see the accessory disclosure indicator on the left. Any idea how to fix that?

**Comment by MortimerGoro** [comment]
Fixed in 1.4.1 ;)

**Comment by MuscleRumble** [comment]
Thanks! :)
