### ISSUE TITLE
bounce effect when swiping

### ISSUE THREAD

**Issue by koenvanderdrift** [MortimerGoro/MGSwipeTableCell#83]
When using the iOS provided Delete button, there is a nice bounce/spring effect when I swipe a cell to the right.

With MGSwipeCell, if I swipe to the right, it looks like the cell stops without bouncing. Is it possible to accomplish this in MGSwipeCell? If not, could this be added?

**Comment by MortimerGoro** [comment]
I have included Easing Functions API in 1.5.1, bounce effect is one of them. You can also implement your own easing functions now. Check the new API. Reopen the issue if you have any problems
