### ISSUE TITLE
can't compile in xcode 6.3

### ISSUE THREAD

**Issue by kalsky** [MortimerGoro/MGSwipeTableCell#84]
it fails in this function: 
-(void) expandSwipe: (MGSwipeDirection) direction animated: (BOOL) animated

at these lines:
__weak typeof(_activeExpansion) w_expantionView = direction == MGSwipeDirectionLeftToRight ? _leftView : _rightView;
__weak typeof(self) weakself = self;

**Comment by erikvillegas** [comment]
Not sure how correct this is, but it works:
__weak MGSwipeButtonsView *w_expantionView = direction == MGSwipeDirectionLeftToRight ? _leftView : _rightView;
 __weak MGSwipeTableCell *weakself = self;

**Comment by MortimerGoro** [comment]
Fixed in 1.4.1 ;)
