### ISSUE TITLE
Swiping stop

### ISSUE THREAD

**Issue by lazarte** [MortimerGoro/MGSwipeTableCell#89]
Hi,

When I swipe my finger to the left and the cell start showing the buttons and will remain my fingers meaning the gesture has not being ended and then suddenly table will reload this will stop the swiping and will not show the buttons. This failed to removed the added data on singleSwipePerTable and will return NO on gestureRecognizerShouldBegin delegate.

**Comment by MortimerGoro** [comment]
Fixed in the latest commit. I'll create the 1.4.2 tag soon.
