### ISSUE TITLE
Snapshot appears along with cell's view

### ISSUE THREAD

**Issue by tjphilli** [MortimerGoro/MGSwipeTableCell#90]
Hey – thanks for making this, it's great. I recently was using cells that were prototype cells coming from storyboards with the library and it was working fine, but I recently switched to doing all programmatic autolayout with custom tableviewcells (subclasses of MGSwipeTableCell of course), and now I'm getting some funky results when swiping. It looks as if the snapshot is slidden left but the tableviewcell's view itself remains. (See photo). I'm just wondering if I'm missing something here or have to do more to configure this to work with custom cells (i.e. not relying on the standard cell.contentView).

![screenshot 2015-04-18 07 46 07](https://cloud.githubusercontent.com/assets/1687500/7215297/496b3ef6-e59f-11e4-9e7d-04def9950b28.png)
![screenshot 2015-04-18 07 46 51](https://cloud.githubusercontent.com/assets/1687500/7215298/496f377c-e59f-11e4-8f9a-ea5a8dd97f4a.png)
![screenshot 2015-04-18 07 45 23](https://cloud.githubusercontent.com/assets/1687500/7215299/496f5a86-e59f-11e4-816c-9afad3043a7f.png)

**Comment by MortimerGoro** [comment]
Hi Trevor,

A similar issue happens when you add your views to the cell itself instead of to the cell's contentView. That might the problem. Check the MailAppDemo, it uses programmatic layout to create the cells. If that's not the problem, can you send me a testcase?

**Comment by tjphilli** [comment]
Great!! That fixed it. I just read Apple's docs which recommends drawing into contentView but I was doing it directly in the tableviewcell itself. Thanks so much!!

**Comment by wy19901227** [comment]
yeah.
