### ISSUE TITLE
Question: Only using the trigger to perform actions

### ISSUE THREAD

**Issue by afriedman94** [MortimerGoro/MGSwipeTableCell#92]
Is it possible to only use the trigger to perform an action? I am trying to recreate the Spotify swipe which allows the user to only perform an action when the trigger is activated. 

At the moment I am able to change the button's color from gray to green when the expansion is triggered, but I am also able to select the utility button when its background is gray and not expanded. 

I would like the button to never stick to a position, and control the button's background color and trigger by the swipeOffset. 

Is this functionality currently possible?

**Comment by mzgaljic** [comment]
You might want to look at issue #72, I got some help with copying the Spotify look...the final result isn't perfect but pretty close.

**Comment by MortimerGoro** [comment]
Fixed in 1.5.1. Check the new Spotify Demo

**Comment by afriedman94** [comment]
awesome. thank you
